version: '3.9'

services:

  mariadb-slave1:
    image: mariadb:lts
    volumes:
      - ./data/slave1:/var/lib/mysql
      - ./conf/slave1.cnf:/etc/mysql/conf.d/mysql.cnf
    command: bash -c "chmod 644 /etc/mysql/conf.d/mysql.cnf && docker-entrypoint.sh mysqld"
    environment:
      TZ: "Asia/jakarta"
      MYSQL_ROOT_PASSWORD: $SLAVE1_ROOT_PASSWORD
    ports:
      - 3302:3302
    networks:
      - bridge

networks:
  bridge:
    driver: bridge