version: '3.9'

services:

  mysql-master:
    image: mariadb:lts
    volumes:
      - ./data/master:/var/lib/mysql
      - ./conf/master.cnf:/etc/mysql/conf.d/mysql.cnf
    command: bash -c "chmod 644 /etc/mysql/conf.d/mysql.cnf && docker-entrypoint.sh mysqld"
    environment:
      TZ: "Asia/jakarta"
      MYSQL_ROOT_PASSWORD: $MASTER_ROOT_PASSWORD
    ports:
      - 3301:3301
    networks:
      - bridge

  # mysql-cron-backup:
  #   image: fradelg/mysql-cron-backup
  #   depends_on:
  #     - mysql-master
  #   volumes:
  #     - ./data/backup:/backup
  #   environment:
  #     - TZ=Asia/Jakarta
  #     - MYSQL_HOST=mysql-master
  #     - MYSQL_USER=root
  #     - MYSQL_PASS=${MASTER_ROOT_PASSWORD}
  #     - MAX_BACKUPS=4
  #     - INIT_BACKUP=0
  #     - CRON_TIME=0 */6 * * *
  #   networks:
  #     - bridge
      
networks:
  bridge:
    driver: bridge