version: '3.9'

services:

  mysql-cron-backup:
    image: fradelg/mysql-cron-backup
    volumes:
      - ./data/backup:/backup
    environment:
      - TZ=Asia/Jakarta
      - MYSQL_PORT=6033
      - MYSQL_HOST=maxscale
      - MYSQL_USER=super_usr
      - MYSQL_PASS=${USER_SUPER_PASSWORD}
      - MAX_BACKUPS=4
      - INIT_BACKUP=0
      - CRON_TIME=0 */6 * * *
    networks:
      - mariadb-network

networks:
  mariadb-network:
    external: true