version: "3.9"

services:
  mariadb-master:
    image: mariadb:10
    volumes:
      - ./data/master:/var/lib/mysql
      - ./conf/master.cnf:/etc/mysql/conf.d/mysql.cnf
    command: bash -c "chmod 644 /etc/mysql/conf.d/mysql.cnf && docker-entrypoint.sh mysqld"
    environment:
      TZ: "Asia/jakarta"
      MYSQL_ROOT_PASSWORD: $MASTER_ROOT_PASSWORD
    ports:
      - 3301:3301
    networks:
      - mysql-network

networks:
  mysql-network:
    external: true
