version: "3.9"

services:
  mariadb-master:
    image: mariadb:11
    deploy:
      replicas: 1
      update_config:
        order: start-first
        delay: 1s
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
        max_attempts: 2
      resources:
        limits:
          cpus: "1.0"
          memory: "1G"
    environment:
      - TZ=$TIMEZONE
      - MYSQL_ROOT_PASSWORD=$MASTER_ROOT_PASSWORD
    volumes:
      - ./data:/var/lib/mysql
      - ./conf/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - 3301:3301
    networks:
      - mysql-network

networks:
  mysql-network:
    external: true
