version: "3.8"

services:
  maxscale:
    image: mariadb/maxscale:latest
    deploy:
      replicas: 1
      update_config:
        order: start-first
        delay: 1s
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
        max_attempts: 2
      resources:
        limits:
          cpus: "1.0"
          memory: "512M"
        reservations:
          cpus: "0.5"
          memory: "256M"
    volumes:
      - ./conf/maxscale.cnf:/etc/maxscale.cnf
    ports:
      - 6033:6033
      - 8989:8989
    networks:
      - mysql-network

networks:
  mysql-network:
    external: true
