version: "3.9"

services:
  mysql-cron-backup:
    image: fradelg/mysql-cron-backup
    deploy:
      replicas: 1
      update_config:
        order: start-first
        delay: 1s
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
        max_attempts: 2
    environment:
      - TZ=Asia/Jakarta
      - MYSQL_PORT=6033
      - MYSQL_HOST=mariadb_maxscale
      - MYSQL_USER=super_usr
      - MYSQL_PASS=${USER_SUPER_PASSWORD}
      - MAX_BACKUPS=4
      - INIT_BACKUP=0
      - CRON_TIME=0 */6 * * *
    volumes:
      - ./backup/mariadb:/backup
    networks:
      - mysql-network

networks:
  mysql-network:
    external: true
