version: "3.9"

services:
  mariadb-slave1:
    image: mariadb:10
    deploy:
      replicas: 1
      update_config:
        order: start-first
        delay: 1s
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
        max_attempts: 2
      resources:
        limits:
          cpus: "1.0"
          memory: "1G"
        reservations:
          cpus: "0.5"
          memory: "512M"
    command: bash -c "chmod 644 /etc/mysql/conf.d/mysql.cnf && docker-entrypoint.sh mysqld"
    environment:
      - TZ=Asia/jakarta
      - MYSQL_ROOT_PASSWORD=${SLAVE1_ROOT_PASSWORD}
    volumes:
      - ./data:/var/lib/mysql
      - ./conf/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    ports:
      - 3302:3302
    networks:
      - mysql-network

networks:
  mysql-network:
    external: true
